import pandas as pd
dropdown_options={
    'year'  :   [{'label':'2000', 'value':'2000'},
                {'label':'2001', 'value':'2001'},
                {'label':'2002', 'value':'2002'},
                {'label':'2003', 'value':'2003'},
                {'label':'2004', 'value':'2004'},
                {'label':'2005', 'value':'2005'},
                {'label':'2006', 'value':'2006'},
                {'label':'2007', 'value':'2007'},
                {'label':'2008', 'value':'2008'},
                {'label':'2009', 'value':'2009'},
                {'label':'2010', 'value':'2010'},
                {'label':'2011', 'value':'2011'},
                {'label':'2012', 'value':'2012'},
                {'label':'2013', 'value':'2013'},
                {'label':'2014', 'value':'2014'},
                {'label':'2015', 'value':'2015'},
                {'label':'2016', 'value':'2016'},
                {'label':'2017', 'value':'2017'},
                {'label':'2018', 'value':'2018'},
                {'label':'2019', 'value':'2019'},
                {'label':'2020', 'value':'2020'},
                {'label':'2021', 'value':'2021'},
                {'label':'2022', 'value':'2022'}],
    'time'  :   [{'label':'1', 'value':'1'},
                {'label':'2', 'value':'2'},
                {'label':'3', 'value':'3'},
                {'label':'4', 'value':'4'},
                {'label':'5', 'value':'5'},
                {'label':'6', 'value':'6'},
                {'label':'7', 'value':'7'},
                {'label':'8', 'value':'8'},
                {'label':'9', 'value':'9'},
                {'label':'10', 'value':'10'},
                {'label':'11', 'value':'11'},
                {'label':'12', 'value':'12'},
                {'label':'13', 'value':'13'},
                {'label':'14', 'value':'14'},
                {'label':'15', 'value':'15'},
                {'label':'16', 'value':'16'},
                {'label':'17', 'value':'17'},
                {'label':'18', 'value':'18'},
                {'label':'19', 'value':'19'},
                {'label':'20', 'value':'20'},
                {'label':'21', 'value':'21'},
                {'label':'22', 'value':'22'},
                {'label':'23', 'value':'23'},
                {'label':'24', 'value':'24'}],
    'operator_contractor':[{'label':'Operator', 'value':'Operator'},
                {'label':'Contractor', 'value':'Contractor'}],
    'accident_date': [{'label':'1', 'value':'1'},
                {'label':'2', 'value':'2'},
                {'label':'3', 'value':'3'},
                {'label':'4', 'value':'4'},
                {'label':'5', 'value':'5'},
                {'label':'6', 'value':'6'},
                {'label':'7', 'value':'7'},
                {'label':'8', 'value':'8'},
                {'label':'9', 'value':'9'},
                {'label':'10', 'value':'10'},
                {'label':'11', 'value':'11'},
                {'label':'12', 'value':'12'},
                {'label':'13', 'value':'13'},
                {'label':'14', 'value':'14'},
                {'label':'15', 'value':'15'},
                {'label':'16', 'value':'16'},
                {'label':'17', 'value':'17'},
                {'label':'18', 'value':'18'},
                {'label':'19', 'value':'19'},
                {'label':'20', 'value':'20'},
                {'label':'21', 'value':'21'},
                {'label':'22', 'value':'22'},
                {'label':'23', 'value':'23'},
                {'label':'24', 'value':'24'},
                {'label':'25', 'value':'25'},
                {'label':'26', 'value':'26'},
                {'label':'27', 'value':'27'},
                {'label':'28', 'value':'28'},
                {'label':'29', 'value':'29'},
                {'label':'30', 'value':'30'},
                {'label':'31', 'value':'31'}],
    'state' :   [{'label':'AL', 'value':'AL'},
                {'label':'KY', 'value':'KY'},
                {'label':'TN', 'value':'TN'},
                {'label':'GA', 'value':'GA'},
                {'label':'WV', 'value':'WV'},
                {'label':'MD', 'value':'MD'},
                {'label':'AZ', 'value':'AZ'},
                {'label':'MT', 'value':'MT'},
                {'label':'CA', 'value':'CA'},
                {'label':'NV', 'value':'NV'},
                {'label':'TX', 'value':'TX'},
                {'label':'AR', 'value':'AR'},
                {'label':'MS', 'value':'MS'},
                {'label':'OK', 'value':'OK'},
                {'label':'ND', 'value':'ND'},
                {'label':'OR', 'value':'OR'},
                {'label':'CO', 'value':'CO'},
                {'label':'SD', 'value':'SD'},
                {'label':'NM', 'value':'NM'},
                {'label':'WY', 'value':'WY'},
                {'label':'KS', 'value':'KS'},
                {'label':'UT', 'value':'UT'},
                {'label':'NE', 'value':'NE'},
                {'label':'CT', 'value':'CT'},
                {'label':'DE', 'value':'DE'},
                {'label':'FL', 'value':'FL'},
                {'label':'ID', 'value':'ID'},
                {'label':'WA', 'value':'WA'},
                {'label':'IL', 'value':'IL'},
                {'label':'IN', 'value':'IN'},
                {'label':'OH', 'value':'OH'},
                {'label':'IA', 'value':'IA'},
                {'label':'MN', 'value':'MN'},
                {'label':'WI', 'value':'WI'},
                {'label':'MO', 'value':'MO'},
                {'label':'VA', 'value':'VA'},
                {'label':'PA', 'value':'PA'},
                {'label':'LA', 'value':'LA'},
                {'label':'ME', 'value':'ME'},
                {'label':'NH', 'value':'NH'},
                {'label':'MA', 'value':'MA'},
                {'label':'MI', 'value':'MI'},
                {'label':'HI', 'value':'HI'},
                {'label':'VT', 'value':'VT'},
                {'label':'NJ', 'value':'NJ'},
                {'label':'NY', 'value':'NY'},
                {'label':'NC', 'value':'NC'},
                {'label':'SC', 'value':'SC'},
                {'label':'RI', 'value':'RI'},
                {'label':'AK', 'value':'AK'},
                {'label':'PR', 'value':'PR'},
                {'label':'VI', 'value':'VI'},
                {'label':'AS', 'value':'AS'},
                {'label':'GU', 'value':'GU'},
                {'label':'MP', 'value':'MP'}],
    'mining_method': [{'label':'M', 'value':'M'},
                 {'label':'C', 'value':'C'}],
    'mining_type':[{'label':'Underground', 'value':'Underground'},
                {'label':'Surface', 'value':'Surface'},
                {'label':'Facility', 'value':'Facility'}],
    'occupation_category': [{'label':'Maintenance man, Mechanic,  Repair/Serviceman, Boilermaker, Fueler, Tire tech, Field service tech', 'value':'Maintenance man, Mechanic,  Repair/Serviceman, Boilermaker, Fueler, Tire tech, Field service tech'},
                {'label':'Truck driver', 'value':'Truck driver'},
                {'label':'Warehouseman, Bagger, Palletizer/Stacker, Store keeper, Packager, Fabricator, Cleaning plant operator', 'value':'Warehouseman, Bagger, Palletizer/Stacker, Store keeper, Packager, Fabricator, Cleaning plant operator'},
                {'label':'Laborer, Blacksmith, Bull gang, Parts runner, Roustabout, Pick-up man, Pitman', 'value':'Laborer, Blacksmith, Bull gang, Parts runner, Roustabout, Pick-up man, Pitman'},
                {'label':'Electrician, Lineman', 'value':'Electrician, Lineman'},
                {'label':'Quality control technician, Laboratory technician, Laboratory assistant', 'value':'Quality control technician, Laboratory technician, Laboratory assistant'},
                {'label':'Greaser, Grease man, Oiler, Lube man, Dragline oiler', 'value':'Greaser, Grease man, Oiler, Lube man, Dragline oiler'},
                {'label':'Bulldozer operator, Universal operator, Heavy equipment operator, Operating engineer', 'value':'Bulldozer operator, Universal operator, Heavy equipment operator, Operating engineer'},
                {'label':'Haul/Off road/Coal/Ore/Pit/Quarry/Rock/Rubber tire truck driver, Transportation truck driver', 'value':'Haul/Off road/Coal/Ore/Pit/Quarry/Rock/Rubber tire truck driver, Transportation truck driver'},
                {'label':'Pumper', 'value':'Pumper'},
                {'label':'LW Propman, Propman helper, Move crew if LW, Move-up man, Jacksetter, Advanceman LW helper', 'value':'LW Propman, Propman helper, Move crew if LW, Move-up man, Jacksetter, Advanceman LW helper'},
                {'label':'Utility man, Errand boy, Service truck operator', 'value':'Utility man, Errand boy, Service truck operator'},
                {'label':'Motorman, Motor person, Swamper, Switchman, Locomotive operator', 'value':'Motorman, Motor person, Swamper, Switchman, Locomotive operator'},
                {'label':'Supply man, Supply worker, Nipper', 'value':'Supply man, Supply worker, Nipper'},
                {'label':'Laborer, Bull gang, Faceman, Parts runner, Roustabout, Roof trimmer/scaler', 'value':'Laborer, Bull gang, Faceman, Parts runner, Roustabout, Roof trimmer/scaler'},
                {'label':'Laborer, Bull gang,  Parts runner, Roustabout, Roof trimmer/scaler', 'value':'Laborer, Bull gang,  Parts runner, Roustabout, Roof trimmer/scaler'},
                {'label':'Bull gang foreman, Labor foreman, Leadman, Section foreman, Shift boss', 'value':'Bull gang foreman, Labor foreman, Leadman, Section foreman, Shift boss'},
                {'label':'Roof bolter, Rock bolter,  Pinner, Mobile roof support operator (MRS)', 'value':'Roof bolter, Rock bolter,  Pinner, Mobile roof support operator (MRS)'},
                {'label':'Longwall operator, Chock operator, Shear operator, Plow operator', 'value':'Longwall operator, Chock operator, Shear operator, Plow operator'},
                {'label':'Beltman, Conveyor man,  Conveyor belt worker, Mobile bridge carrierman, Feeder operator, Conveyor rider', 'value':'Beltman, Conveyor man,  Conveyor belt worker, Mobile bridge carrierman, Feeder operator, Conveyor rider'},
                {'label':'Examiner, Fire boss, Pre-shift examiner, Mine examiner', 'value':'Examiner, Fire boss, Pre-shift examiner, Mine examiner'},
                {'label':'Dryer operator, Kiln operator,  Dry plant operator,  Fluid operator, Bed dryer operator', 'value':'Dryer operator, Kiln operator,  Dry plant operator,  Fluid operator, Bed dryer operator'},
                {'label':'Blaster, Shooter, Shotfirer, Explosive worker, Powder gang/monkey', 'value':'Blaster, Shooter, Shotfirer, Explosive worker, Powder gang/monkey'},
                {'label':'Section foreman, Bullgang foreman, Labor foreman, Leadman, Shift boss', 'value':'Section foreman, Bullgang foreman, Labor foreman, Leadman, Shift boss'},
                {'label':'Shuttle car operator, Mantrip operator, Ramcar operator, Rail runner, Buggy operator', 'value':'Shuttle car operator, Mantrip operator, Ramcar operator, Rail runner, Buggy operator'},
                {'label':'Drill operator', 'value':'Drill operator'},
                {'label':'create_allocation_result_flat_gurobi', 'value':'create_allocation_result_flat_gurobi'},
                {'label':'Stopping builder, Ventilation man, Mason man, Overcast', 'value':'Stopping builder, Ventilation man, Mason man, Overcast'},
                {'label':'Welder (shop)', 'value':'Welder (shop)'},
                {'label':'Continuous miner operator, Coal mole operator', 'value':'Continuous miner operator, Coal mole operator'},
                {'label':'Outside foreman, Leadman', 'value':'Outside foreman, Leadman'},
                {'label':'Electrician helper', 'value':'Electrician helper'},
                {'label':'Mechanic helper', 'value':'Mechanic helper'},
                {'label':'Carpenter', 'value':'Carpenter'},
                {'label':'Drill helper', 'value':'Drill helper'},
                {'label':'Utility man, Shift tech, Service/Dump truck operator', 'value':'Utility man, Shift tech, Service/Dump truck operator'},
                {'label':'Security guard, Watchman', 'value':'Security guard, Watchman'},
                {'label':'Miner, Prospector, NEC', 'value':'Miner, Prospector, NEC'},
                {'label':'Driver, Jeep driver, Tractor operator', 'value':'Driver, Jeep driver, Tractor operator'},
                {'label':'Crusher attendant/operator, Pan feeder operator/worker', 'value':'Crusher attendant/operator, Pan feeder operator/worker'},
                {'label':'Safety director', 'value':'Safety director'},
                {'label':'Shopman repair cars, Mechanic', 'value':'Shopman repair cars, Mechanic'},
                {'label':'Miner, NEC', 'value':'Miner, NEC'},
                {'label':'Crane operator, Mobile equipment operator (MEO), Dragline operator, Dropball operator, Rigger', 'value':'Crane operator, Mobile equipment operator (MEO), Dragline operator, Dropball operator, Rigger'},
                {'label':'Car dropper, Car shake out operator', 'value':'Car dropper, Car shake out operator'},
                {'label':'Ledgeman/hand, Quarry man', 'value':'Ledgeman/hand, Quarry man'},
                {'label':'Front-end loader, Scraper-loader operator, Pan operator, Payloader, Scraper rig operator', 'value':'Front-end loader, Scraper-loader operator, Pan operator, Payloader, Scraper rig operator'},
                {'label':'Stone finishing and sizing personnel, Stone/Rock cut/Polish/Saw operator, Splitter, Cutter, Trimmer', 'value':'Stone finishing and sizing personnel, Stone/Rock cut/Polish/Saw operator, Splitter, Cutter, Trimmer'},
                {'label':'Rodman, Surveyor/Transit helper', 'value':'Rodman, Surveyor/Transit helper'},
                {'label':'Plumber, Pipefitter, Millwright', 'value':'Plumber, Pipefitter, Millwright'},
                {'label':'Brakeman, Roperider, Car runner, Spotterman, Snapper, Trip rider, Car rider, Flagman', 'value':'Brakeman, Roperider, Car runner, Spotterman, Snapper, Trip rider, Car rider, Flagman'},
                {'label':'Coal sampler', 'value':'Coal sampler'},
                {'label':'Mine manager, Mine foreman, Mine owner', 'value':'Mine manager, Mine foreman, Mine owner'},
                {'label':'Fireman - locomotive, Railroad clam operator, Timekeeper, Yard engine operator', 'value':'Fireman - locomotive, Railroad clam operator, Timekeeper, Yard engine operator'},
                {'label':'Scalper-screen operator', 'value':'Scalper-screen operator'},
                {'label':'Assayer, Geologist, Metallurgist, Engineer, Engineer management', 'value':'Assayer, Geologist, Metallurgist, Engineer, Engineer management'},
                {'label':'Coal/ore shovel operator,  Shoveler,  Power shoveler', 'value':'Coal/ore shovel operator,  Shoveler,  Power shoveler'},
                {'label':'Backhoe operator, Trackhoe operator, Crane operator', 'value':'Backhoe operator, Trackhoe operator, Crane operator'},
                {'label':'Assistant mine foreman, Assistant mine manager', 'value':'Assistant mine foreman, Assistant mine manager'},
                {'label':'Hoistman, Hoist operator', 'value':'Hoistman, Hoist operator'},
                {'label':'Rock duster', 'value':'Rock duster'},
                {'label':'Hand loader, Hand trammer', 'value':'Hand loader, Hand trammer'},
                {'label':'Barge/Boat/Dredge/Towbarge/Towboat/Leach operator, Riverman, Deck hand', 'value':'Barge/Boat/Dredge/Towbarge/Towboat/Leach operator, Riverman, Deck hand'},
                {'label':'Weighman, Scale person', 'value':'Weighman, Scale person'},
                {'label':'Silo operator, Bin puller, Truck loader', 'value':'Silo operator, Bin puller, Truck loader'},
                {'label':'Bagging, Package operator', 'value':'Bagging, Package operator'},
                {'label':'Belt foreman, Maintenance foreman, Maintenance supervisor', 'value':'Belt foreman, Maintenance foreman, Maintenance supervisor'},
                {'label':'Stoper miner', 'value':'Stoper miner'},
                {'label':'Water truck operator', 'value':'Water truck operator'},
                {'label':'Master mechanic, Foreman, Supervisor', 'value':'Master mechanic, Foreman, Supervisor'},
                {'label':'Continuous miner helper, Coal mole helper, Bridgeman', 'value':'Continuous miner helper, Coal mole helper, Bridgeman'},
                {'label':'Discontinued 1/31/2014.  Several other codes cover Scoop Car Operator', 'value':'Discontinued 1/31/2014.  Several other codes cover Scoop Car Operator'},
                {'label':'Welder (non-shop)', 'value':'Welder (non-shop)'},
                {'label':'Scoop tram operator, Load/Haul/Dump operator', 'value':'Scoop tram operator, Load/Haul/Dump operator'},
                {'label':'Forklift operator', 'value':'Forklift operator'},
                {'label':'Groundman, Yardman', 'value':'Groundman, Yardman'},
                {'label':'Grader operator, Roadgrader operator', 'value':'Grader operator, Roadgrader operator'},
                {'label':'Master electrician', 'value':'Master electrician'},
                {'label':'Superintendent', 'value':'Superintendent'},
                {'label':'Rock driller', 'value':'Rock driller'},
                {'label':'Apprentice, Trainee', 'value':'Apprentice, Trainee'},
                {'label':'Driller operator', 'value':'Driller operator'},
                {'label':'Scoop car/Scooptram operator, Load/Haul/Dump (LHD) operator, Teletram operator', 'value':'Scoop car/Scooptram operator, Load/Haul/Dump (LHD) operator, Teletram operator'},
                {'label':'Supply man, Nipper', 'value':'Supply man, Nipper'},
                {'label':'Tipple/Top lander/Skip dumper operator, Binman, Topman', 'value':'Tipple/Top lander/Skip dumper operator, Binman, Topman'},
                {'label':'Timberman', 'value':'Timberman'},
                {'label':'Driller, Highwall operator, Highwall drill operator', 'value':'Driller, Highwall operator, Highwall drill operator'},
                {'label':'Auger operator, Auger Crew supervisor', 'value':'Auger operator, Auger Crew supervisor'},
                {'label':'Rotary bucket excavator operator', 'value':'Rotary bucket excavator operator'},
                {'label':'Rotary drill operator (electric/hydraulic)', 'value':'Rotary drill operator (electric/hydraulic)'},
                {'label':'Mason', 'value':'Mason'},
                {'label':'Wireman, Communications man', 'value':'Wireman, Communications man'},
                {'label':'Clerk, Timekeeper, Office worker, Director of sales', 'value':'Clerk, Timekeeper, Office worker, Director of sales'},
                {'label':'Cleanup man, Cleanup worker', 'value':'Cleanup man, Cleanup worker'},
                {'label':'Mineral industrial safety officer', 'value':'Mineral industrial safety officer'},
                {'label':'Backhoe operator, Trackhoe operator', 'value':'Backhoe operator, Trackhoe operator'},
                {'label':'Training specialist', 'value':'Training specialist'},
                {'label':'Front-end loader operator', 'value':'Front-end loader operator'},
                {'label':'Brattice man/worker', 'value':'Brattice man/worker'},
                {'label':'Refuse truck driver, Backfill truck driver, Stock pile truck driver', 'value':'Refuse truck driver, Backfill truck driver, Stock pile truck driver'},
                {'label':'Gathering arm loader operator,  Loading machine operator, Joy loader operator', 'value':'Gathering arm loader operator,  Loading machine operator, Joy loader operator'},
                {'label':'Welder', 'value':'Welder'},
                {'label':'Roof bolter helper, Rock bolter helper, Pinner helper', 'value':'Roof bolter helper, Rock bolter helper, Pinner helper'},
                {'label':'Safety representative', 'value':'Safety representative'},
                {'label':'Building repair man, Maintenance', 'value':'Building repair man, Maintenance'},
                {'label':'Dry screening plant operator, Screen house operator', 'value':'Dry screening plant operator, Screen house operator'},
                {'label':'Dispatcher', 'value':'Dispatcher'},
                {'label':'Car trimmer, Car loader, Bin puller, Truck loader', 'value':'Car trimmer, Car loader, Bin puller, Truck loader'},
                {'label':'Belt cleaner, Picker', 'value':'Belt cleaner, Picker'},
                {'label':'Trackman, Track worker, Track gang', 'value':'Trackman, Track worker, Track gang'},
                {'label':'Cutting machine operator, Ripper, Universal operator', 'value':'Cutting machine operator, Ripper, Universal operator'},
                {'label':'Warehouse, Supply handler', 'value':'Warehouse, Supply handler'},
                {'label':'Leaching operator', 'value':'Leaching operator'},
                {'label':'Education specialist', 'value':'Education specialist'},
                {'label':'Trespasser', 'value':'Trespasser'},
                {'label':'Loader head operator, Roscoe operator', 'value':'Loader head operator, Roscoe operator'},
                {'label':'Fine coal plant operator', 'value':'Fine coal plant operator'},
                {'label':'Steel worker, Iron metal worker, Iron worker', 'value':'Steel worker, Iron metal worker, Iron worker'},
                {'label':'Water circuit operator, Slurry operator, Mix operator, Pump operator worker', 'value':'Water circuit operator, Slurry operator, Mix operator, Pump operator worker'},
                {'label':'Grizzly worker, Grizzly tender, Grizzlyman, Chute puller, Chute tapper', 'value':'Grizzly worker, Grizzly tender, Grizzlyman, Chute puller, Chute tapper'},
                {'label':'Inspector', 'value':'Inspector'},
                {'label':'Stall driver', 'value':'Stall driver'},
                {'label':'Hydrate plant operator', 'value':'Hydrate plant operator'},
                {'label':'Scraper-loader operator', 'value':'Scraper-loader operator'},
                {'label':'Raise borer operator', 'value':'Raise borer operator'},
                {'label':'Draftsman, Surveyor/Transit work supervisor', 'value':'Draftsman, Surveyor/Transit work supervisor'},
                {'label':'Mechanical  scaling worker', 'value':'Mechanical  scaling worker'},
                {'label':'Belt vulcanizer', 'value':'Belt vulcanizer'},
                {'label':'Vacuum filter operator, Flotation mill/Concentrator operator, Flotation plant operator', 'value':'Vacuum filter operator, Flotation mill/Concentrator operator, Flotation plant operator'},
                {'label':'Lab Technician', 'value':'Lab Technician'},
                {'label':'Underground transportation trainee', 'value':'Underground transportation trainee'},
                {'label':'Driller, Highwall helper, Highwall drill helper', 'value':'Driller, Highwall helper, Highwall drill helper'},
                {'label':'Ball/Rod/Pebble/Hand/Limestone/Dry mill operator, Roller operator', 'value':'Ball/Rod/Pebble/Hand/Limestone/Dry mill operator, Roller operator'},
                {'label':'Drift miner', 'value':'Drift miner'},
                {'label':'Shaftcrew, Shaft repair, Skip tender, Station tender', 'value':'Shaftcrew, Shaft repair, Skip tender, Station tender'},
                {'label':'Rotary dump operator, Car dump operator', 'value':'Rotary dump operator, Car dump operator'},
                {'label':'Mucking machine operator', 'value':'Mucking machine operator'},
                {'label':'Coal dump operator', 'value':'Coal dump operator'},
                {'label':'Ground controller', 'value':'Ground controller'},
                {'label':'Washer operator, Sizing operator', 'value':'Washer operator, Sizing operator'},
                {'label':'Headgate operator', 'value':'Headgate operator'},
                {'label':'Lampman, Lamp person', 'value':'Lampman, Lamp person'},
                {'label':'Transit man, Surveyor/Transit worker', 'value':'Transit man, Surveyor/Transit worker'},
                {'label':'Raise miner', 'value':'Raise miner'},
                {'label':'Fan attendant', 'value':'Fan attendant'},
                {'label':'Loading machine/Gather arm loader helper', 'value':'Loading machine/Gather arm loader helper'},
                {'label':'Hand scaler', 'value':'Hand scaler'},
                {'label':'Janitor', 'value':'Janitor'},
                {'label':'Painter', 'value':'Painter'},
                {'label':'Diamond drill operator, Core driller, Exploration driller, Longhole driller, Prospect driller', 'value':'Diamond drill operator, Core driller, Exploration driller, Longhole driller, Prospect driller'},
                {'label':'Bobcat operator', 'value':'Bobcat operator'},
                {'label':'Shopman', 'value':'Shopman'},
                {'label':'Hand trammer', 'value':'Hand trammer'},
                {'label':'Cage/Cager/Station attendant', 'value':'Cage/Cager/Station attendant'},
                {'label':'Hammer mill operator, Breaker mill operator, Jaw mill operator', 'value':'Hammer mill operator, Breaker mill operator, Jaw mill operator'},
                {'label':'Cement worker, Concrete worker,  Form man, Mandoseal man', 'value':'Cement worker, Concrete worker,  Form man, Mandoseal man'},
                {'label':'Refinery worker', 'value':'Refinery worker'},
                {'label':'Machinist', 'value':'Machinist'},
                {'label':'Auger helper', 'value':'Auger helper'},
                {'label':'Grader operator', 'value':'Grader operator'},
                {'label':'Shaft repair, Skip tender, Station tender', 'value':'Shaft repair, Skip tender, Station tender'},
                {'label':'Skip tender, Station tender', 'value':'Skip tender, Station tender'},
                {'label':'Jackhammer operator, Chiphammer operator', 'value':'Jackhammer operator, Chiphammer operator'},
                {'label':'Cutting machine helper, Undercutter operator helper', 'value':'Cutting machine helper, Undercutter operator helper'},
                {'label':'Sweeper operator', 'value':'Sweeper operator'},
                {'label':'Coal strip operator', 'value':'Coal strip operator'},
                {'label':'Froth cell operator, Flotation mill operator, Concetrator operator', 'value':'Froth cell operator, Flotation mill operator, Concetrator operator'},
                {'label':'Drill helper, Chuck tender', 'value':'Drill helper, Chuck tender'},
                {'label':'Waterboy', 'value':'Waterboy'},
                {'label':'Chute blaster, Rockman, Hang-up man, Raise blaster', 'value':'Chute blaster, Rockman, Hang-up man, Raise blaster'},
                {'label':'Boomcat operator, Stripping shovel operator', 'value':'Boomcat operator, Stripping shovel operator'},
                {'label':'Mine safety instructor', 'value':'Mine safety instructor'},
                {'label':'Sandfiller (dry)', 'value':'Sandfiller (dry)'},
                {'label':'Self-propelled compactor operator', 'value':'Self-propelled compactor operator'},
                {'label':'Boom operator', 'value':'Boom operator'},
                {'label':'Cage/Cager/Station attendant, Aerial tram (outside only)', 'value':'Cage/Cager/Station attendant, Aerial tram (outside only)'},
                {'label':'Sandfiller (wet), Slurry operator', 'value':'Sandfiller (wet), Slurry operator'},
                {'label':'Union representative', 'value':'Union representative'},
                {'label':'Shotcrete, Gunite worker', 'value':'Shotcrete, Gunite worker'},
                {'label':'Pelletizing operator', 'value':'Pelletizing operator'},
                {'label':'Car loader', 'value':'Car loader'},
                {'label':'Tailgate operator', 'value':'Tailgate operator'},
                {'label':'Face worker-Shaft/Slope sinking', 'value':'Face worker-Shaft/Slope sinking'},
                {'label':'Bit sharpener, Bit grinder, Grinder', 'value':'Bit sharpener, Bit grinder, Grinder'},
                {'label':'Battery station operator', 'value':'Battery station operator'},
                {'label':'Slusher operator', 'value':'Slusher operator'},
                {'label':'Chainman, Surveyor/Transit helper', 'value':'Chainman, Surveyor/Transit helper'},
                {'label':'ROOF BOLTER (MOUNTED) (RETURN SIDE)', 'value':'ROOF BOLTER (MOUNTED) (RETURN SIDE)'},
                {'label':'Power shovel operator', 'value':'Power shovel operator'},
                {'label':'Hoist operator helper', 'value':'Hoist operator helper'},
                {'label':'Jumbo percussion drill operator', 'value':'Jumbo percussion drill operator'},
                {'label':'Trip rider, Swamper', 'value':'Trip rider, Swamper'},
                {'label':'Ramcar operator', 'value':'Ramcar operator'},
                {'label':'Wagon drill operator, Air-track driller, Carriage mounted drill operator', 'value':'Wagon drill operator, Air-track driller, Carriage mounted drill operator'},
                {'label':'Water line man', 'value':'Water line man'},
                {'label':'Supplyman', 'value':'Supplyman'},
                {'label':'Hangup worker, Chute blaster', 'value':'Hangup worker, Chute blaster'}],


    'activity_category':[{'label':'Hand tools (powered)', 'value':'Hand tools (powered)'},
                                    {'label':'Handling coal, Rock, Ore', 'value':'Handling coal, Rock, Ore'},
                                    {'label':'Climb scaffolds, Ladders', 'value':'Climb scaffolds, Ladders'},
                                    {'label':'Lay or repair railroad track', 'value':'Lay or repair railroad track'},
                                    {'label':'Handling supplies or material', 'value':'Handling supplies or material'},
                                    {'label':'Hand tools (not powered)', 'value':'Hand tools (not powered)'},
                                    {'label':'Enter/work in bins, Silos', 'value':'Enter/work in bins, Silos'},
                                    {'label':'Machine maintenance', 'value':'Machine maintenance'},
                                    {'label':'Other, NEC', 'value':'Other, NEC'},
                                    {'label':'Move non-self-propelled equip', 'value':'Move non-self-propelled equip'},
                                    {'label':'Walking, Running', 'value':'Walking, Running'},
                                    {'label':'Getting on or off equipment', 'value':'Getting on or off equipment'},
                                    {'label':'Inspect equipment or mine', 'value':'Inspect equipment or mine'},
                                    {'label':'NO VALUE FOUND', 'value':'NO VALUE FOUND'},
                                    {'label':'Haulage or Dump truck', 'value':'Haulage or Dump truck'},
                                    {'label':'Electrical maintenance', 'value':'Electrical maintenance'},
                                    {'label':'Mantrip', 'value':'Mantrip'},
                                    {'label':'Unknown', 'value':'Unknown'},
                                    {'label':'Roof bolter, Tramming', 'value':'Roof bolter, Tramming'},
                                    {'label':'Roof bolter, NEC', 'value':'Roof bolter, NEC'},
                                    {'label':'Load-haul-dump (UG)', 'value':'Load-haul-dump (UG)'},
                                    {'label':'Handling timber', 'value':'Handling timber'},
                                    {'label':'Grinding', 'value':'Grinding'},
                                    {'label':'Set or remove brattice', 'value':'Set or remove brattice'},
                                    {'label':'Environmental tests or checks', 'value':'Environmental tests or checks'},
                                    {'label':'Hand load, Hand shoveling', 'value':'Hand load, Hand shoveling'},
                                    {'label':'Set, Remove, Relocate props', 'value':'Set, Remove, Relocate props'},
                                    {'label':'Move power cable', 'value':'Move power cable'},
                                    {'label':'Ride equipment', 'value':'Ride equipment'},
                                    {'label':'Underground equipment, NEC', 'value':'Underground equipment, NEC'},
                                    {'label':'Shuttle car, Ram car, Buggy', 'value':'Shuttle car, Ram car, Buggy'},
                                    {'label':'Welding or cutting', 'value':'Welding or cutting'},
                                    {'label':'Supervise', 'value':'Supervise'},
                                    {'label':'Power shovel, Dragline', 'value':'Power shovel, Dragline'},
                                    {'label':'Escaping a hazard', 'value':'Escaping a hazard'},
                                    {'label':'Mill equipment', 'value':'Mill equipment'},
                                    {'label':'Surface construction, NEC', 'value':'Surface construction, NEC'},
                                    {'label':'Surface equipment, NEC', 'value':'Surface equipment, NEC'},
                                    {'label':'Bulldozer', 'value':'Bulldozer'},
                                    {'label':'Couple or uncouple mine car', 'value':'Couple or uncouple mine car'},
                                    {'label':'Idle', 'value':'Idle'},
                                    {'label':'Utility truck, Water trucks', 'value':'Utility truck, Water trucks'},
                                    {'label':'Front-end loader', 'value':'Front-end loader'},
                                    {'label':'Handling explosives', 'value':'Handling explosives'},
                                    {'label':'Bar down, Includes scaling', 'value':'Bar down, Includes scaling'},
                                    {'label':'Mucking machine', 'value':'Mucking machine'},
                                    {'label':'Working with chemicals', 'value':'Working with chemicals'},
                                    {'label':'Blow gun, Airlance', 'value':'Blow gun, Airlance'},
                                    {'label':'Chute, Pull or free', 'value':'Chute, Pull or free'},
                                    {'label':'Observe operations', 'value':'Observe operations'},
                                    {'label':'Scraper, Pan scraper', 'value':'Scraper, Pan scraper'},
                                    {'label':'Conveyor belt', 'value':'Conveyor belt'},
                                    {'label':'Change house, Bathing', 'value':'Change house, Bathing'},
                                    {'label':'Fork lift', 'value':'Fork lift'},
                                    {'label':'Drill face, Rib, Side, Down', 'value':'Drill face, Rib, Side, Down'},
                                    {'label':'Timbering, Build cribs', 'value':'Timbering, Build cribs'},
                                    {'label':'Crawling, Kneeling', 'value':'Crawling, Kneeling'},
                                    {'label':'Continuous miner', 'value':'Continuous miner'},
                                    {'label':'Rock dust machine', 'value':'Rock dust machine'},
                                    {'label':'Advance roof support-longwall', 'value':'Advance roof support-longwall'},
                                    {'label':'Roof bolter, Inserting bolt', 'value':'Roof bolter, Inserting bolt'},
                                    {'label':'Horseplay', 'value':'Horseplay'},
                                    {'label':'Cement work, Gunite crew', 'value':'Cement work, Gunite crew'},
                                    {'label':'Travel ', 'value':'Travel'},
                                    {'label':'Roof bolter, Drilling', 'value':'Roof bolter, Drilling'},
                                    {'label':'Ventilation maintenance', 'value':'Ventilation maintenance'},
                                    {'label':'Rerail equipment, Sprag', 'value':'Rerail equipment, Sprag'},
                                    {'label':'Office and lab work, Clerical', 'value':'Office and lab work, Clerical'},
                                    {'label':'Grader', 'value':'Grader'},
                                    {'label':'Longwall, Shear, Plow', 'value':'Longwall, Shear, Plow'},
                                    {'label':'Hang or reposition tubing', 'value':'Hang or reposition tubing'},
                                    {'label':'Caging, Operate elevator', 'value':'Caging, Operate elevator'},
                                    {'label':'Clean up - UG only', 'value':'Clean up - UG only'},
                                    {'label':'Wet down working place', 'value':'Wet down working place'},
                                    {'label':'Blasting, Shoot coal', 'value':'Blasting, Shoot coal'},
                                    {'label':'Locomotive', 'value':'Locomotive'},
                                    {'label':'Working with solvents', 'value':'Working with solvents'},
                                    {'label':'Double jack', 'value':'Double jack'},
                                    {'label':'Cross over (conveyor)', 'value':'Cross over (conveyor)'},
                                    {'label':'Cutting machine', 'value':'Cutting machine'},
                                    {'label':'Sand fill', 'value':'Sand fill'},
                                    {'label':'Spot rail cars, Trip riding', 'value':'Spot rail cars, Trip riding'},
                                    {'label':'Crusher, Breaker', 'value':'Crusher, Breaker'},
                                    {'label':'Impactor', 'value':'Impactor'},
                                    {'label':'Block or chock mine cars', 'value':'Block or chock mine cars'},
                                    {'label':'Barge, Boat, Dredge', 'value':'Barge, Boat, Dredge'},
                                    {'label':'Climb in piled material', 'value':'Climb in piled material'},
                                    {'label':'Slusher', 'value':'Slusher'},
                                    {'label':'Remove/position hydraulic jack', 'value':'Remove/position hydraulic jack'},
                                    {'label':'Jitney', 'value':'Jitney'},
                                    {'label':'Accident recovery', 'value':'Accident recovery'},
                                    {'label':'Climb in raise, Shaft, Manway', 'value':'Climb in raise, Shaft, Manway'},
                                    {'label':'Auger (surface)', 'value':'Auger (surface)'},
                                    {'label':'Working with noxious materials', 'value':'Working with noxious materials'},
                                    {'label':'Loading machine', 'value':'Loading machine'},
                                    {'label':'Auger (UG)', 'value':'Auger (UG)'},
                                    {'label':'Shortwall', 'value':'Shortwall'},
                                    {'label':'Brush floor: Remove rock', 'value':'Brush floor: Remove rock'},
                                    {'label':'Assault and battery, Murder', 'value':'Assault and battery, Murder'}],
    'nature_of_injury':[{'label':'CUT,LACER,PUNCT-OPN WOUND', 'value':'CUT,LACER,PUNCT-OPN WOUND'},
                                        {'label':'SPRAIN,STRAIN RUPT DISC', 'value':'SPRAIN,STRAIN RUPT DISC'},
                                        {'label':'SCRATCH,ABRASION,SUPERFCL', 'value':'SCRATCH,ABRASION,SUPERFCL'},
                                        {'label':'UNCLASSIFIED,NOT DETERMED', 'value':'UNCLASSIFIED,NOT DETERMED'},
                                        {'label':'BURN,CHEMICL-FUME,COMPOUN', 'value':'BURN,CHEMICL-FUME,COMPOUN'},
                                        {'label':'HERNIA;RUPTURE', 'value':'HERNIA;RUPTURE'},
                                        {'label':'AMPUTATION OR ENUCLEATION', 'value':'AMPUTATION OR ENUCLEATION'},
                                        {'label':'HEATSTROK,SUNSTR,HT EXHAU', 'value':'HEATSTROK,SUNSTR,HT EXHAU'},
                                        {'label':'CONTUSN,BRUISE,INTAC SKIN', 'value':'CONTUSN,BRUISE,INTAC SKIN'},
                                        {'label':'FRACTURE,CHIP', 'value':'FRACTURE,CHIP'},
                                        {'label':'JOINT,TENDON,MUSCL INFLAM', 'value':'JOINT,TENDON,MUSCL INFLAM'},
                                        {'label':'ELECT.ARC BURN-NOT CONTAC', 'value':'ELECT.ARC BURN-NOT CONTAC'},
                                        {'label':'OTHER INJURY,NEC', 'value':'OTHER INJURY,NEC'},
                                        {'label':'CRUSHING', 'value':'CRUSHING'},
                                        {'label':'DUST IN EYES', 'value':'DUST IN EYES'},
                                        {'label':'MULTIPLE INJURIES', 'value':'MULTIPLE INJURIES'},
                                        {'label':'POISONING,SYSTEMIC', 'value':'POISONING,SYSTEMIC'},
                                        {'label':'DISLOCATION', 'value':'DISLOCATION'},
                                        {'label':'HEARING LOSS OR IMPAIRMNT', 'value':'HEARING LOSS OR IMPAIRMNT'},
                                        {'label':'CONCUSSION-BRAIN,CEREBRAL', 'value':'CONCUSSION-BRAIN,CEREBRA'},
                                        {'label':'DERMATITIS,RASH,SKIN INFL', 'value':'DERMATITIS,RASH,SKIN INFL'},
                                        {'label':'BURN OR SCALD (HEAT)', 'value':'BURN OR SCALD (HEAT)'},
                                        {'label':'HEART ATTACK', 'value':'HEART ATTACK'},
                                        {'label':'SILICOSIS', 'value':'SILICOSIS'},
                                        {'label':'OCCUPATIONAL DISEASES,NEC', 'value':'OCCUPATIONAL DISEASES,NEC'},
                                        {'label':'PNEUMOCONIOSIS,BLACK LUNG', 'value':'PNEUMOCONIOSIS,BLACK LUNG'},
                                        {'label':'ELECT SHOCK,ELECTROCUTION', 'value':'ELECT SHOCK,ELECTROCUTION'},
                                        {'label':'ELECTRIC BURN-CNTACT BURN', 'value':'ELECTRIC BURN-CNTACT BURN'},
                                        {'label':'SUFFOC,SMOK INHILAT,DROWN', 'value':'SUFFOC,SMOK INHILAT,DROWN'},
                                        {'label':'OTH RADIATION EFFECT,NEC', 'value':'OTH RADIATION EFFECT,NEC'},
                                        {'label':'CEREBRAL HEMORAGE-NT CCUS', 'value':'CEREBRAL HEMORAGE-NT CCUS'},
                                        {'label':'FREEZNG,FROSTBITE,LO TEMP', 'value':'FREEZNG,FROSTBITE,LO TEMP'},
                                        {'label':'CONTAGIOUS,INFECT DISEASE', 'value':'CONTAGIOUS,INFECT DISEASE'},
                                        {'label':'ASBESTOSIS', 'value':'ASBESTOSIS'},
                                        {'label':'OTHER PNEUMOCONIOSIS,NEC', 'value':'OTHER PNEUMOCONIOSIS,NEC'},
                                        {'label':'SUNBURN', 'value':'SUNBURN'},
                                        {'label':'LASER BURN', 'value':'LASER BURN'},
                                        {'label':'LUNG CANCER,IONIZNG RDATN', 'value':'LUNG CANCER,IONIZNG RDATN'}],
    'injury_body_part':[{'label':'FINGER(S)/THUMB', 'value':'FINGER(S)/THUMB'},
                                        {'label':'FOREARM/ULNAR/RADIUS', 'value':'FOREARM/ULNAR/RADIUS'},
                                        {'label':'BACK (MUSCLES/SPINE/S-CORD/TAILBONE)', 'value':'BACK (MUSCLES/SPINE/S-CORD/TAILBONE)'},
                                        {'label':'HAND (NOT WRIST OR FINGERS)', 'value':'HAND (NOT WRIST OR FINGERS)'},
                                        {'label':'KNEE/PATELLA', 'value':'KNEE/PATELLA'},
                                        {'label':'SHOULDERS (COLLARBONE/CLAVICLE/SCAPULA)', 'value':'SHOULDERS (COLLARBONE/CLAVICLE/SCAPULA)'},
                                        {'label':'ABDOMEN/INTERNAL ORGANS', 'value':'ABDOMEN/INTERNAL ORGANS'},
                                        {'label':'EYE(S) OPTIC NERVE/VISON', 'value':'EYE(S) OPTIC NERVE/VISON'},
                                        {'label':'ANKLE', 'value':'ANKLE'},
                                        {'label':'MULTIPLE PARTS (MORE THAN ONE MAJOR)', 'value':'MULTIPLE PARTS (MORE THAN ONE MAJOR)'},
                                        {'label':'TRUNK, MULTIPLE PARTS', 'value':'TRUNK, MULTIPLE PARTS'},
                                        {'label':'HIPS (PELVIS/ORGANS/KIDNEYS/BUTTOCKS)', 'value':'HIPS (PELVIS/ORGANS/KIDNEYS/BUTTOCKS)'},
                                        {'label':'BODY SYSTEMS', 'value':'BODY SYSTEMS'},
                                        {'label':'ELBOW', 'value':'ELBOW'},
                                        {'label':'UPPER EXTREMITIES, MULTIPLE', 'value':'UPPER EXTREMITIES, MULTIPLE'},
                                        {'label':'HEAD,NEC', 'value':'HEAD,NEC'},
                                        {'label':'FOOT(NOT ANKLE/TOE)/TARSUS/METATARSUS', 'value':'FOOT(NOT ANKLE/TOE)/TARSUS/METATARSUS'},
                                        {'label':'MOUTH/LIP/TEETH/TONGUE/THROAT/TASTE', 'value':'MOUTH/LIP/TEETH/TONGUE/THROAT/TASTE'},
                                        {'label':'SCALP', 'value':'SCALP'},
                                        {'label':'WRIST', 'value':'WRIST'},
                                        {'label':'CHEST (RIBS/BREAST BONE/CHEST ORGNS)', 'value':'CHEST (RIBS/BREAST BONE/CHEST ORGNS)'},
                                        {'label':'LOWER LEG/TIBIA/FIBULA', 'value':'LOWER LEG/TIBIA/FIBULA'},
                                        {'label':'NECK', 'value':'NECK'},
                                        {'label':'LOWER EXTREMITIES, MULTIPLE PARTS', 'value':'LOWER EXTREMITIES, MULTIPLE PARTS'},
                                        {'label':'FACE, MULTIPLE PARTS', 'value':'FACE, MULTIPLE PARTS'},
                                        {'label':'FACE,NEC', 'value':'FACE,NEC'},
                                        {'label':'JAW INCLUDE CHIN', 'value':'JAW INCLUDE CHIN'},
                                        {'label':'ARM,NEC', 'value':'ARM,NEC'},
                                        {'label':'TOE(S)/PHALANGES', 'value':'TOE(S)/PHALANGES'},
                                        {'label':'ARM, MULTIPLE PARTS', 'value':'ARM, MULTIPLE PARTS'},
                                        {'label':'LEG, NEC', 'value':'LEG, NEC'},
                                        {'label':'EAR(S) INTERNAL & HEARING', 'value':'EAR(S) INTERNAL & HEARING'},
                                        {'label':'UPPER ARM/HUMERUS', 'value':'UPPER ARM/HUMERUS'},
                                        {'label':'BRAIN', 'value':'BRAIN'},
                                        {'label':'THIGH/FEMUR', 'value':'THIGH/FEMUR'},
                                        {'label':'UNCLASSIFIED', 'value':'UNCLASSIFIED'},
                                        {'label':'NOSE/NASAL PASSAGES/SINUS/SMELL', 'value':'NOSE/NASAL PASSAGES/SINUS/SMELL'},
                                        {'label':'EAR(S) EXTERNAL', 'value':'EAR(S) EXTERNAL'},
                                        {'label':'HEAD, MULTIPLE PARTS', 'value':'HEAD, MULTIPLE PARTS'},
                                        {'label':'LEG, MULTIPLE PARTS', 'value':'LEG, MULTIPLE PARTS'},
                                        {'label':'SKULL', 'value':'SKULL'},
                                        {'label':'TRUNK,NEC', 'value':'TRUNK,NEC'},
                                        {'label':'EAR(S) INTERNAL & EXTERNAL', 'value':'EAR(S) INTERNAL & EXTERNAL'},
                                        {'label':'BODY PARTS, NEC', 'value':'BODY PARTS, NEC'},
                                        {'label':'LOWER EXTREMITIES,NEC', 'value':'LOWER EXTREMITIES,NEC'},
                                        {'label':'LOWER EXTREMITIES,NEC', 'value':'LOWER EXTREMITIES,NEC'}]
}

def select_all_check(key,values):
    if 'select_all' in values :
        return pd.DataFrame(dropdown_options[key])['value'].to_list()
    else:
        return values